version: '3.1'
services:
  api:
    environment:
      GIN_MODE: ${GIN_MODE}
      PORT: ${PORT}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      DB_CONNECTION_STRING: ${DB_CONNECTION_STRING}
      SESSION_KEY: ${SESSION_KEY}
    image: ${COMPONENT}_api:latest
    ports:
      - "8000:8000"
    networks:
      - budgeting_network
  redis:
    image: redis
    # ports:
    #   - "6380:6379"
    networks:
      - budgeting_network
  database:
    image: postgres:alpine
    volumes:
      - ./migrations:/migrations
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASS}
      PGPASSWORD: ${DB_PASS}
      PGDATA: /data
    env_file: .env
    # ports:
    #   - "5433:5432"
    networks:
      - budgeting_network
networks:
  budgeting_network:
    external: true
